# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1077, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RM = QtWidgets.QPushButton(self.centralwidget)
        self.RM.setGeometry(QtCore.QRect(208, 210, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RM.setFont(font)
        self.RM.setObjectName("RM")
        self.EP = QtWidgets.QPushButton(self.centralwidget)
        self.EP.setGeometry(QtCore.QRect(210, 290, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EP.setFont(font)
        self.EP.setObjectName("EP")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(830, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logout.setFont(font)
        self.logout.setObjectName("logout")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(390, 710, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.RM_2 = QtWidgets.QPushButton(self.centralwidget)
        self.RM_2.setGeometry(QtCore.QRect(160, 440, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RM_2.setFont(font)
        self.RM_2.setObjectName("RM_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 150, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 380, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.RM_3 = QtWidgets.QPushButton(self.centralwidget)
        self.RM_3.setGeometry(QtCore.QRect(160, 530, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RM_3.setFont(font)
        self.RM_3.setObjectName("RM_3")
        self.RM_4 = QtWidgets.QPushButton(self.centralwidget)
        self.RM_4.setGeometry(QtCore.QRect(638, 200, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RM_4.setFont(font)
        self.RM_4.setObjectName("RM_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 140, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(622, 380, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.RM_5 = QtWidgets.QPushButton(self.centralwidget)
        self.RM_5.setGeometry(QtCore.QRect(640, 280, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RM_5.setFont(font)
        self.RM_5.setObjectName("RM_5")
        self.RM_6 = QtWidgets.QPushButton(self.centralwidget)
        self.RM_6.setGeometry(QtCore.QRect(650, 440, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RM_6.setFont(font)
        self.RM_6.setObjectName("RM_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RM.setText(_translate("MainWindow", "Raw Material"))
        self.EP.setText(_translate("MainWindow", "Shade Number"))
        self.logout.setText(_translate("MainWindow", "Logout"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.RM_2.setText(_translate("MainWindow", "Add New Raw Material"))
        self.label.setText(_translate("MainWindow", "Enter Transactions : "))
        self.label_2.setText(_translate("MainWindow", "Add new Materail Details : "))
        self.RM_3.setText(_translate("MainWindow", "Add New Shade Number"))
        self.RM_4.setText(_translate("MainWindow", "Raw Material"))
        self.label_3.setText(_translate("MainWindow", "View Stock Details :"))
        self.label_4.setText(_translate("MainWindow", "Enter Sale Details :"))
        self.RM_5.setText(_translate("MainWindow", "Shade Number"))
        self.RM_6.setText(_translate("MainWindow", "Shade Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())