# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\rm_add.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back_add_rm = QtWidgets.QPushButton(self.centralwidget)
        self.back_add_rm.setGeometry(QtCore.QRect(20, 20, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_add_rm.setFont(font)
        self.back_add_rm.setObjectName("back_add_rm")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rm_addtable = QtWidgets.QTableWidget(self.centralwidget)
        self.rm_addtable.setGeometry(QtCore.QRect(190, 250, 541, 251))
        self.rm_addtable.setRowCount(8)
        self.rm_addtable.setColumnCount(3)
        self.rm_addtable.setObjectName("rm_addtable")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_addtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_addtable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_addtable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_addtable.setItem(7, 1, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.rm_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.rm_confirm.setGeometry(QtCore.QRect(750, 500, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rm_confirm.setFont(font)
        self.rm_confirm.setObjectName("rm_confirm")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 90, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.date = QtWidgets.QLineEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(640, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date.setFont(font)
        self.date.setObjectName("date")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 90, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.rm_transaction_id = QtWidgets.QLineEdit(self.centralwidget)
        self.rm_transaction_id.setGeometry(QtCore.QRect(220, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rm_transaction_id.setFont(font)
        self.rm_transaction_id.setObjectName("rm_transaction_id")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 160, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.rw_remark = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_remark.setGeometry(QtCore.QRect(660, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_remark.setFont(font)
        self.rw_remark.setObjectName("rw_remark")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(560, 160, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.rm_customer = QtWidgets.QComboBox(self.centralwidget)
        self.rm_customer.setGeometry(QtCore.QRect(220, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rm_customer.setFont(font)
        self.rm_customer.setEditable(True)
        self.rm_customer.setObjectName("rm_customer")
        self.rm_customer.addItem("")
        self.rm_customer.setItemText(0, "")
        self.rm_customer.addItem("")
        self.rm_customer.addItem("")
        self.rm_customer.addItem("")
        self.rm_customer.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_add_rm.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "Raw Material"))
        item = self.rm_addtable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product Code"))
        item = self.rm_addtable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.rm_addtable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity"))
        __sortingEnabled = self.rm_addtable.isSortingEnabled()
        self.rm_addtable.setSortingEnabled(False)
        self.rm_addtable.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.rm_confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_4.setText(_translate("MainWindow", "Date :"))
        self.label_5.setText(_translate("MainWindow", "Transaction ID : "))
        self.label_6.setText(_translate("MainWindow", "Customer Name:"))
        self.label_7.setText(_translate("MainWindow", "Remark :"))
        self.rm_customer.setItemText(1, _translate("MainWindow", "Rajesh"))
        self.rm_customer.setItemText(2, _translate("MainWindow", "Nishit"))
        self.rm_customer.setItemText(3, _translate("MainWindow", "Nilay"))
        self.rm_customer.setItemText(4, _translate("MainWindow", "Parth"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
