# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\rm_modify.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rm_modify_remark = QtWidgets.QLineEdit(self.centralwidget)
        self.rm_modify_remark.setGeometry(QtCore.QRect(640, 190, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rm_modify_remark.setFont(font)
        self.rm_modify_remark.setObjectName("rm_modify_remark")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.rm_view_table = QtWidgets.QTableWidget(self.centralwidget)
        self.rm_view_table.setGeometry(QtCore.QRect(170, 270, 541, 251))
        self.rm_view_table.setRowCount(8)
        self.rm_view_table.setColumnCount(3)
        self.rm_view_table.setObjectName("rm_view_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(7, 1, item)
        self.rm_modify_date = QtWidgets.QLineEdit(self.centralwidget)
        self.rm_modify_date.setGeometry(QtCore.QRect(620, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rm_modify_date.setFont(font)
        self.rm_modify_date.setObjectName("rm_modify_date")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 110, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.rm_modify_customer = QtWidgets.QComboBox(self.centralwidget)
        self.rm_modify_customer.setGeometry(QtCore.QRect(200, 190, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rm_modify_customer.setFont(font)
        self.rm_modify_customer.setEditable(True)
        self.rm_modify_customer.setObjectName("rm_modify_customer")
        self.rm_modify_customer.addItem("")
        self.rm_modify_customer.setItemText(0, "")
        self.rm_modify_customer.addItem("")
        self.rm_modify_customer.addItem("")
        self.rm_modify_customer.addItem("")
        self.rm_modify_customer.addItem("")
        self.rw_modify_transaction_id = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_modify_transaction_id.setGeometry(QtCore.QRect(200, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_modify_transaction_id.setFont(font)
        self.rw_modify_transaction_id.setObjectName("rw_modify_transaction_id")
        self.back_view_rm = QtWidgets.QPushButton(self.centralwidget)
        self.back_view_rm.setGeometry(QtCore.QRect(30, 40, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_view_rm.setFont(font)
        self.back_view_rm.setObjectName("back_view_rm")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 40, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 180, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.rm_modify_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.rm_modify_confirm.setGeometry(QtCore.QRect(700, 570, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rm_modify_confirm.setFont(font)
        self.rm_modify_confirm.setObjectName("rm_modify_confirm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Transaction ID : "))
        item = self.rm_view_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product Code"))
        item = self.rm_view_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.rm_view_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity"))
        __sortingEnabled = self.rm_view_table.isSortingEnabled()
        self.rm_view_table.setSortingEnabled(False)
        self.rm_view_table.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "Customer Name:"))
        self.label_4.setText(_translate("MainWindow", "Date :"))
        self.rm_modify_customer.setItemText(1, _translate("MainWindow", "Rajesh"))
        self.rm_modify_customer.setItemText(2, _translate("MainWindow", "Nishit"))
        self.rm_modify_customer.setItemText(3, _translate("MainWindow", "Nilay"))
        self.rm_modify_customer.setItemText(4, _translate("MainWindow", "Parth"))
        self.back_view_rm.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "Raw Material"))
        self.pushButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.label_7.setText(_translate("MainWindow", "Remark :"))
        self.rm_modify_confirm.setText(_translate("MainWindow", "Modify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
