# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\rm_stock_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back_view_rm = QtWidgets.QPushButton(self.centralwidget)
        self.back_view_rm.setGeometry(QtCore.QRect(50, 30, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_view_rm.setFont(font)
        self.back_view_rm.setObjectName("back_view_rm")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.rm_view_table = QtWidgets.QTableWidget(self.centralwidget)
        self.rm_view_table.setGeometry(QtCore.QRect(110, 260, 561, 381))
        self.rm_view_table.setRowCount(100)
        self.rm_view_table.setColumnCount(4)
        self.rm_view_table.setObjectName("rm_view_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(3, item)
        self.rw_view_ending_date = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_view_ending_date.setGeometry(QtCore.QRect(730, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_view_ending_date.setFont(font)
        self.rw_view_ending_date.setText("")
        self.rw_view_ending_date.setObjectName("rw_view_ending_date")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rw_view_starting_date = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_view_starting_date.setGeometry(QtCore.QRect(280, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_view_starting_date.setFont(font)
        self.rw_view_starting_date.setText("")
        self.rw_view_starting_date.setObjectName("rw_view_starting_date")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(540, 160, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 160, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.rw_view_stock_code = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_view_stock_code.setGeometry(QtCore.QRect(280, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_view_stock_code.setFont(font)
        self.rw_view_stock_code.setText("")
        self.rw_view_stock_code.setObjectName("rw_view_stock_code")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 90, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.rw_view_stock_name = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_view_stock_name.setGeometry(QtCore.QRect(730, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_view_stock_name.setFont(font)
        self.rw_view_stock_name.setText("")
        self.rw_view_stock_name.setObjectName("rw_view_stock_name")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 90, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.rw_view_starting_date_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_view_starting_date_2.setGeometry(QtCore.QRect(790, 680, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_view_starting_date_2.setFont(font)
        self.rw_view_starting_date_2.setText("")
        self.rw_view_starting_date_2.setObjectName("rw_view_starting_date_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(630, 670, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_view_rm.setText(_translate("MainWindow", "Back"))
        self.pushButton.setText(_translate("MainWindow", "Back to Main Menu"))
        item = self.rm_view_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Transaction ID"))
        item = self.rm_view_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.rm_view_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "In"))
        item = self.rm_view_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Out"))
        self.label_3.setText(_translate("MainWindow", "Raw Material"))
        self.label_9.setText(_translate("MainWindow", "Enter ending date : "))
        self.label_8.setText(_translate("MainWindow", "Enter starting date : "))
        self.label_10.setText(_translate("MainWindow", "Enter product code : "))
        self.label_11.setText(_translate("MainWindow", "Product Name : "))
        self.label_12.setText(_translate("MainWindow", "Closing Stock :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
