# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\rm_view_by_custom.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rm_view_table = QtWidgets.QTableWidget(self.centralwidget)
        self.rm_view_table.setGeometry(QtCore.QRect(50, 200, 781, 381))
        self.rm_view_table.setRowCount(100)
        self.rm_view_table.setColumnCount(7)
        self.rm_view_table.setObjectName("rm_view_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.rm_view_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.rm_view_table.setItem(7, 5, item)
        self.back_view_rm = QtWidgets.QPushButton(self.centralwidget)
        self.back_view_rm.setGeometry(QtCore.QRect(10, 40, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_view_rm.setFont(font)
        self.back_view_rm.setObjectName("back_view_rm")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 40, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(590, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.rw_view_starting_date = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_view_starting_date.setGeometry(QtCore.QRect(230, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_view_starting_date.setFont(font)
        self.rw_view_starting_date.setText("")
        self.rw_view_starting_date.setObjectName("rw_view_starting_date")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 110, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.rw_view_ending_date = QtWidgets.QLineEdit(self.centralwidget)
        self.rw_view_ending_date.setGeometry(QtCore.QRect(680, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rw_view_ending_date.setFont(font)
        self.rw_view_ending_date.setText("")
        self.rw_view_ending_date.setObjectName("rw_view_ending_date")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(490, 110, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.rm_view_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Transaction ID"))
        item = self.rm_view_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.rm_view_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Customer"))
        item = self.rm_view_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Remark"))
        item = self.rm_view_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Product Code"))
        item = self.rm_view_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.rm_view_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Quantity"))
        __sortingEnabled = self.rm_view_table.isSortingEnabled()
        self.rm_view_table.setSortingEnabled(False)
        self.rm_view_table.setSortingEnabled(__sortingEnabled)
        self.back_view_rm.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "Raw Material"))
        self.pushButton.setText(_translate("MainWindow", "Back to Main Menu"))
        self.label_8.setText(_translate("MainWindow", "Enter starting date : "))
        self.label_9.setText(_translate("MainWindow", "Enter ending date : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
