# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shade_stock_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back_view_rm = QtWidgets.QPushButton(self.centralwidget)
        self.back_view_rm.setGeometry(QtCore.QRect(10, 10, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_view_rm.setFont(font)
        self.back_view_rm.setObjectName("back_view_rm")
        self.shade_view_closing = QtWidgets.QLineEdit(self.centralwidget)
        self.shade_view_closing.setGeometry(QtCore.QRect(770, 750, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shade_view_closing.setFont(font)
        self.shade_view_closing.setText("")
        self.shade_view_closing.setObjectName("shade_view_closing")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(610, 740, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(520, 230, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(520, 160, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(590, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.shade_view_table = QtWidgets.QTableWidget(self.centralwidget)
        self.shade_view_table.setGeometry(QtCore.QRect(90, 330, 561, 381))
        self.shade_view_table.setRowCount(100)
        self.shade_view_table.setColumnCount(4)
        self.shade_view_table.setObjectName("shade_view_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.shade_view_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.shade_view_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.shade_view_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.shade_view_table.setHorizontalHeaderItem(3, item)
        self.shade_view_stock_name = QtWidgets.QLineEdit(self.centralwidget)
        self.shade_view_stock_name.setGeometry(QtCore.QRect(710, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shade_view_stock_name.setFont(font)
        self.shade_view_stock_name.setText("")
        self.shade_view_stock_name.setObjectName("shade_view_stock_name")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 160, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.shade_view_ending_date = QtWidgets.QLineEdit(self.centralwidget)
        self.shade_view_ending_date.setGeometry(QtCore.QRect(710, 240, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shade_view_ending_date.setFont(font)
        self.shade_view_ending_date.setText("")
        self.shade_view_ending_date.setObjectName("shade_view_ending_date")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 230, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.shade_view_stock_code = QtWidgets.QLineEdit(self.centralwidget)
        self.shade_view_stock_code.setGeometry(QtCore.QRect(260, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shade_view_stock_code.setFont(font)
        self.shade_view_stock_code.setText("")
        self.shade_view_stock_code.setObjectName("shade_view_stock_code")
        self.shade_view_starting_date = QtWidgets.QLineEdit(self.centralwidget)
        self.shade_view_starting_date.setGeometry(QtCore.QRect(260, 240, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shade_view_starting_date.setFont(font)
        self.shade_view_starting_date.setText("")
        self.shade_view_starting_date.setObjectName("shade_view_starting_date")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(310, 90, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.shade_view_stock_shade_number = QtWidgets.QLineEdit(self.centralwidget)
        self.shade_view_stock_shade_number.setGeometry(QtCore.QRect(500, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shade_view_stock_shade_number.setFont(font)
        self.shade_view_stock_shade_number.setText("")
        self.shade_view_stock_shade_number.setObjectName("shade_view_stock_shade_number")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_view_rm.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "Shade Number"))
        self.label_12.setText(_translate("MainWindow", "Closing Stock :"))
        self.label_9.setText(_translate("MainWindow", "Enter ending date : "))
        self.label_11.setText(_translate("MainWindow", "Product Name : "))
        self.pushButton.setText(_translate("MainWindow", "Back to Main Menu"))
        item = self.shade_view_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Transaction ID"))
        item = self.shade_view_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.shade_view_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "In"))
        item = self.shade_view_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Out"))
        self.label_10.setText(_translate("MainWindow", "Enter product code : "))
        self.label_8.setText(_translate("MainWindow", "Enter starting date : "))
        self.label_13.setText(_translate("MainWindow", "Enter shade number : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
